# Generated by Django 5.0.2 on 2024-02-27 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acara',
            fields=[
                ('nama', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('tempat', models.CharField(max_length=255)),
                ('waktu_mulai', models.DateTimeField()),
                ('waktu_selesai', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Panitia',
            fields=[
                ('nama', models.CharField(max_length=255)),
                ('fakultas', models.CharField(max_length=255)),
                ('angkatan', models.CharField(max_length=255)),
                ('jurusan', models.CharField(max_length=255)),
                ('npm', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('jenis', models.CharField(default='panitia', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DivisiBPH',
            fields=[
                ('nama', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DivisiPI',
            fields=[
                ('nama', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Kelompok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Perusahaan',
            fields=[
                ('nama', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='BPH',
            fields=[
                ('panitia_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.panitia')),
                ('jabatan', models.CharField(max_length=255)),
                ('divisi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pengurusBPH', to='main.divisibph')),
            ],
            options={
                'abstract': False,
            },
            bases=('main.panitia',),
        ),
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('nama', models.CharField(max_length=255)),
                ('fakultas', models.CharField(max_length=255)),
                ('angkatan', models.CharField(max_length=255)),
                ('jurusan', models.CharField(max_length=255)),
                ('npm', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('jalur_masuk', models.CharField(max_length=255)),
                ('kelompok', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mentee', to='main.kelompok')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('nama', models.CharField(max_length=255)),
                ('fakultas', models.CharField(max_length=255)),
                ('angkatan', models.CharField(max_length=255)),
                ('jurusan', models.CharField(max_length=255)),
                ('npm', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('kelompok', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='mentor', to='main.kelompok')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pembicara',
            fields=[
                ('nama', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('acara', models.ManyToManyField(related_name='pembicara', to='main.acara')),
            ],
        ),
        migrations.CreateModel(
            name='Spon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paket', models.CharField(max_length=255)),
                ('acara', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.acara')),
                ('perusahaan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.perusahaan')),
            ],
        ),
        migrations.CreateModel(
            name='Rapat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu', models.DateTimeField()),
                ('tempat', models.CharField(max_length=255)),
                ('materi', models.TextField()),
                ('divisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapat', to='main.divisibph')),
                ('hadir', models.ManyToManyField(related_name='hadir_rapat', to='main.bph')),
            ],
        ),
        migrations.CreateModel(
            name='PengurusInti',
            fields=[
                ('panitia_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.panitia')),
                ('divisi', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pengurusInti', to='main.divisipi')),
            ],
            options={
                'abstract': False,
            },
            bases=('main.panitia',),
        ),
        migrations.CreateModel(
            name='Mentoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu', models.DateTimeField()),
                ('tempat', models.CharField(max_length=255)),
                ('materi', models.CharField(max_length=255)),
                ('hadir', models.ManyToManyField(related_name='mentee_hadir', to='main.mentee')),
                ('kelompok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentoring', to='main.kelompok')),
            ],
            options={
                'unique_together': {('kelompok', 'materi')},
            },
        ),
    ]
