# Generated by Django 5.0.2 on 2024-02-27 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spon',
            new_name='Sponsor',
        ),
    ]
