# Generated by Django 5.0.2 on 2024-02-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_spon_sponsor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembicara',
            name='acara',
        ),
        migrations.AddField(
            model_name='acara',
            name='pembicara',
            field=models.ManyToManyField(related_name='pembicara', to='main.pembicara'),
        ),
    ]
