# Generated by Django 5.0.2 on 2024-02-29 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_pembicara_acara_acara_pembicara'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rapat',
            old_name='materi',
            new_name='kesimpulan',
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='acara',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.acara'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='perusahaan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.perusahaan'),
        ),
    ]
